// Generated by CoffeeScript 1.3.3
(function() {
  var FileParse, argv, file, parse;

  argv = require('optimist').argv;

  FileParse = require('./file_parse').FileParse;

  file = argv._[0];

  parse = new FileParse(file);

  parse.run();

}).call(this);
