// Generated by CoffeeScript 1.3.3
(function() {
  var FileParse, Glob, argv, fileglob, fileglobs, glob, _i, _len;

  argv = require('optimist').argv;

  Glob = require('glob').Glob;

  FileParse = require('./file_parse').FileParse;

  fileglobs = argv._;

  for (_i = 0, _len = fileglobs.length; _i < _len; _i++) {
    fileglob = fileglobs[_i];
    glob = new Glob(fileglob, {
      strict: true
    });
    glob.on('match', function(match) {
      var parse;
      parse = new FileParse(match);
      return parse.run();
    });
  }

}).call(this);
